# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
  steps:
  - template: build/azure-steps.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
  steps:
  - template: build/azure-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
  steps:
  # apparently Chrome is already there: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#google-chrome
  # - script: choco install wget --no-progress --limit-output
  #   displayName: 'Install wget (to Download Chrome)'
  # - script: bash ./lighthouse-core/scripts/download-chrome.sh
  #   displayName: 'Download Chrome'
  #   env:
  #     LIGHTHOUSE_CHROMIUM_PATH: $(agent.homeDirectory)\chrome-win32\chrome.exe
  - template: build/azure-steps.yml


# how bou dat?
